-- Users table for authentication and authorization
CREATE TABLE IF NOT EXISTS USER (
  USER_ID INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  ROLE ENUM('admin', 'organizer', 'attendee') DEFAULT 'attendee',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Venues table for event locations
CREATE TABLE IF NOT EXISTS VENUE (
  VENUE_ID INT PRIMARY KEY AUTO_INCREMENT,
  VENUE_NAME VARCHAR(255) NOT NULL,
  ADDRESS TEXT NOT NULL,
  CAPACITY INT,
  CONTACT_INFO VARCHAR(255),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Categories for event types
CREATE TABLE IF NOT EXISTS CATEGORY (
  CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
  CATEGORY_NAME VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPTION TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tags for event keywords
CREATE TABLE IF NOT EXISTS TAG (
  TAG_ID INT PRIMARY KEY AUTO_INCREMENT,
  TAG_NAME VARCHAR(50) UNIQUE NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Junction table for event tags (many-to-many relationship)
CREATE TABLE IF NOT EXISTS EVENT_TAG (
  EVENT_ID INT NOT NULL,
  TAG_ID INT NOT NULL,
  PRIMARY KEY (EVENT_ID, TAG_ID),
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID) ON DELETE CASCADE,
  FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID) ON DELETE CASCADE
);

-- Improved Events table with foreign keys
CREATE TABLE IF NOT EXISTS EVENT (
  EVENT_ID INT PRIMARY KEY AUTO_INCREMENT,
  EVENT_NAME VARCHAR(255) NOT NULL,
  EVENT_DATE DATETIME NOT NULL,
  LOCATION VARCHAR(255),
  DESCRIPTION TEXT,
  ORGANIZER_ID INT,
  VENUE_ID INT,
  CATEGORY_ID INT,
  CAPACITY INT,
  STATUS ENUM('draft', 'published', 'cancelled') DEFAULT 'draft',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (ORGANIZER_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
  FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID) ON DELETE SET NULL,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE SET NULL
);

-- Updated Attendees table with user linkage
CREATE TABLE IF NOT EXISTS ATTENDEE (
  ATTENDEE_ID INT PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  NUMBER VARCHAR(15) NOT NULL,
  EVENT_ID INT NOT NULL,
  STATUS ENUM('registered', 'confirmed', 'cancelled', 'attended') DEFAULT 'registered',
  REGISTERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID) ON DELETE CASCADE
);

-- Insert default categories
INSERT IGNORE INTO CATEGORY (CATEGORY_NAME, DESCRIPTION) VALUES
('Workshop', 'Hands-on learning sessions and practical training'),
('Seminar', 'Educational talks and presentations'),
('Meetup', 'Casual networking and community gatherings'),
('Concert', 'Live music performances and entertainment'),
('Conference', 'Large-scale professional gatherings'),
('Webinar', 'Online educational sessions'),
('Exhibition', 'Product showcases and displays'),
('Sports', 'Athletic events and competitions');

-- Insert default tags
INSERT IGNORE INTO TAG (TAG_NAME) VALUES
('AI'), ('Networking'), ('Technology'), ('Business'), ('Music'), ('Art'), ('Health'), ('Education'),
('Career'), ('Innovation'), ('Startup'), ('Design'), ('Marketing'), ('Finance'), ('Science'), ('Engineering');
